### ISSUE TITLE
$(document).ready(function() {}代码冗余度很大的问题？

### ISSUE THREAD

**Issue by UncleYangsir** [UncleYangsir/wuliuzha#16]
checkPhoneAndSms.js代码中，为注册、短信登录、找回密码中“免费获取验证码”按键渲染效果中，三个按键其实分别对应着发送三种不同模板的短信验证码，这个过程基本上只有wlzSmsNumber短信模板编号是不同的，其他都基本上都是相同的，而我现在用的就是最笨的复制粘贴的方法，重复写了特别多的代码，问题就在于:
`$(document).ready(function() {}`
对于这种形式的函数，如何传入一些特定的参数，就像function a(code){}，使得我可以直接将不同的wlzSmsNumber传入，就可以直接节省接近140行的代码；[坐标链接](https://github.com/UncleYangsir/wuliuzha/blob/master/public/javascripts/checkPhoneAndSms.js#L74)

**Comment by zhonggy** [comment]
1. 这跟$(document).ready(function() {});没任何关系。去掉这个的影响，你的代码还是一堆冗余代码。
```javascript
$(document).ready(function() {
    $('#get_sms_retrieve').click(function() {});
    $('#get_sms_register').click(function() {});
    $('#get_sms_btn_login').click(function() {});
});
```

2. 传参还可以用全局变量。最外层声明var a="hello"（最好写window.a = "hello";原因跟后面一样）；到处都可以调用a，最好显式调用window.a，这样方便阅读，知道哪些是全局变量；

3. 你的问题也不是传参问题，就是不会抽象。直接把重复的代码声明称一个方法：
```javascript
var ajaxSendSms = function (wlzSmsNumber) {
    // 获取id为phone的页面元素，并获取其提示信息
    var phone = $('#phone').val().trim();
    ...
    if (phone != "" ) {
        ...
    } else {
        ...
    }
}

// 调用
$('#get_sms_register').click(function() {
    ajaxSendSms("89705093");
});
```

**Comment by UncleYangsir** [comment]
好的，姐夫
