### ISSUE TITLE
物流闸注册界面关于用户名和手机号是否已存在的问题？（用JQuery库解决）

### ISSUE THREAD

**Issue by UncleYangsir** [UncleYangsir/wuliuzha#4]
问题：我想要在注册界面实现，刚刚输入完用户名或者手机号后，可以检测到用户输入的是否在数据库已经存在；一般而言，表单内单个input的内容检测会直接交给JS文件检测，其格式是否有误等等，可在这个过程如果要检测输入的内容是否在我们的数据库中时，我就不知道该如何是好？

个人想法：直接通在JS文件内，创建UsersDAO的对象，调用UsersDAO的checkUsersName(String name)方法来检查；可是目前这个想法是要在JS内完成，所以个人在网络上搜索也不知道该怎么做，所以停滞不前。

**Comment by zhonggy** [comment]
用户名可以重复，不是唯一，手机号是唯一。

**方法1.** 

使用JS，发送一个HTTP请求到服务器端(建议使用jQuery库的[getJSON](http://api.jquery.com/jquery.getjson/))，服务器端写一个接口(JSON格式)，专门用来检测手机号是否存在，如GET /check_phone_exist?phone=15000000000，返回JOSN格式(查文档怎么写JSON接口，平时我们只用了HTML格式，没用过JSON格式)：
```json
{
    "exists":  true
}
```

**Comment by zhonggy** [comment]
方法2.

提交表单之后，才提示错误，如果检查手机已经存在，回到注册界面，提示错误信息。

**Comment by zhonggy** [comment]
建议加一个唯一索引，限制phone不能重复，插入重复手机号会报错：
```sql
ALTER TABLE users ADD UNIQUE INDEX user_unique_index (phone);
```

**Comment by zhonggy** [comment]
我表达是否清晰？如果思路不清晰的话要沟通，不要闭门造车。
