### ISSUE TITLE
写入数据库时statement.setString()问题（LIKE和=的区别、通配符、LIKE和数据库索引的关系）

### ISSUE THREAD

**Issue by UncleYangsir** [UncleYangsir/wuliuzha#6]
今天早上出现了一个问题，无论如何导入，数据库查询始终显示没有输入值的错误，结果花了一个半小时也没找到漏洞原因；下午在代码内遍布了System.out.println("序号"+"每个位置相关输出")终于找到了原因。
```
String insertUsersSQL = "SELECT phone FROM users WHERE  phone = ?";     
PreparedStatement statement = connection.prepareStatement(insertUsersSQL);                
statement.setString(1, users.getPhone());
System.out.println(statement);
```
其输出的结果为：
![image](https://user-images.githubusercontent.com/30687851/29859729-117f34f6-8d96-11e7-85c3-dd1161ad9a83.png)
于是我重新书写了这段代码为：
```
String insertUsersSQL = "SELECT phone FROM users WHERE  phone = ?";
PreparedStatement statement = connection.prepareStatement(insertUsersSQL);                
statement.setString(1,"%" + users.getPhone()+ "%");
System.out.println(statement);
```
![image](https://user-images.githubusercontent.com/30687851/29859779-448cfe28-8d96-11e7-8de1-c8d357a8cc6d.png)
问题就解决了，主要差别就是在setString里面，之前小说站加%号可以继续导入，可是现在加%反倒无法识别了；

**Comment by zhonggy** [comment]
没搞清楚LIKE和=的区别，小说站也不会=和%组合使用。LIKE才需要%，这个场景下，百分号是一种「通配符」，查查。

**Comment by zhonggy** [comment]
LIKE的性能慢很多

**Comment by UncleYangsir** [comment]
在MySQL中，例如`SELECT phone FROM users WHERE phone LIKE ?`如果?的内容为'123456'，此时LIKE的含义就相当于"=",当?的内容为%123456%,就相当于搜索phone内包含像123456类似的字段，而不是"="；
[通配符](https://zh.wikipedia.org/wiki/%E9%80%9A%E9%85%8D%E7%AC%A6)： 
# 计算机
在计算机（软件）技术中，通配符可用于代替字符。 通常地，星号“*”匹配0个或以上的字符，问号“?”匹配1个字符。
## 文件和目录
在CP/M、DOS、Microsoft Windows和类Unix操作系统中描述文件名(或路径)时，星号(*)匹配零个或多个任意字符、问号(?)匹配零个或不多于问号个数的任意字符。如：123??? 将匹配 1231 或 12313，但不会匹配 123991991。在Unix shell和Windows PowerShell中，方括号("["和"]")括起来的字符范围匹配在此范围内的任意字符，例如：[A-Za-z] 匹配任意的大小写字母。Unix shells 可以在用括号括起来的指定字符前加一个"!"来表示否定。匹配到多个文件或路径的通配符模式称为glob扩展。
## 数据库
在SQL中，通配符可用于"LIKE"表达式中，百分号(%)匹配零个或多个字符，下划线(_)匹配单个字符。Transact-SQL中还支持使用方括号("["和"]")来匹配列表集和字符范围，在前面加一个 ^ 表示否定，将匹配所有未在括号中指定的字符。在Microsoft Access中，通配符可用于"LIKE"表达式中，星号(*)匹配零个或多个字符，问号(?)匹配单个字符。在 SAP 中加号(+)匹配一个字符。
## 正则表达式
在正则表达式中，英文句号(.)匹配单个字符，结合一个星号(.*)匹配任意多个字符。
## 效率
在针对较长字符串匹配或对大量的字符串进行匹配时应该注意，后匹配(ABC*)比前匹配(*ABC)有着有着十分明显的效率优势。因为后匹配(ABC*)可以立即排除那些不是已"A"开头的记录，接着排除第二个字符不是"B"的；而前匹配(*ABC)需要尝试匹配每一个字符，至少直到找到了"ABC"。在一些需要高性能的环境应该尽量避免使用前匹配，或者通过其他条件筛选减少了数据量后再使用前匹配搜索。
## 相关
[正则表达式](https://zh.wikipedia.org/wiki/%E6%AD%A3%E5%88%99%E8%A1%A8%E8%BE%BE%E5%BC%8F)

**Comment by zhonggy** [comment]
LIKE的性能跟索引有关，数据库索引是什么？LIKE是否能利用索引？

**Comment by UncleYangsir** [comment]
数据库索引：
[维基百科](https://zh.wikipedia.org/wiki/%E6%95%B0%E6%8D%AE%E5%BA%93%E7%B4%A2%E5%BC%95)：数据库索引，是数据库管理系统中一个排序的数据结构，以协助快速查询、更新数据库表中数据。
[百度百科](https://baike.baidu.com/item/%E6%95%B0%E6%8D%AE%E5%BA%93%E7%B4%A2%E5%BC%95)：索引是对数据库表中一列或多列的值进行排序的一种结构，使用索引可快速访问数据库表中的特定信息。如果想按特定职员的姓来查找他或她，则与在表中搜索所有的行相比，索引有助于更快地获取信息。
索引的一个主要目的就是加快检索表中数据的方法，亦即能协助信息搜索者尽快的找到符合限制条件的记录ID的辅助数据结构。

我个人觉得，数据库索引最常用的方法就是想二叉树一样排序要索引的值，例如有a~z个字母，通过数据库索引它会变成一个二叉树结构的图形，如果要找到字幕k，就相当于从树顶开始，判断是二叉树的左还是右，往下一层继续，有点像二分法一样，而数据库的索引对于数据库的性能提升有很大帮助，根据这个特性，我觉得LIKE可以利用索引极快的找到所需要的，例如LIKE = %cdef%,根据索引特性，搜索的范围就在二叉树连续包含cdef的字段内，这极大减小了搜索区域；

**Comment by zhonggy** [comment]
LIKE的说法不对，如果建立了phone索引的情况下：

1. WHERE phone = '15000000000'是可以用到索引的；
2. WHERE phone LIKE '150%'是可以用到索引的；
3. WHERE phone LIKE '%150%'是不能用到索引的；

可以想想为什么。

**Comment by UncleYangsir** [comment]
这个是因为在MySQL里面，"%"用在LIKE里面表示模糊查询吧，我发现LIKE '%150' 和LIKE '%150%'都是不能用索引，原因应该是当通配符"%"在前面时，数据库默认直接启动了为150前的模糊查询，这会使索引失效，可能因为和索引的原理有冲突，而LIKE ‘150%’就可以直接使用索引，就像二叉树分类一样，系统会自动判别这个位置该不该用索引，自动将查询范围限制在1，5，0，然后再查询，才大大增加了查询效率；我还发现直接使用LIKE ‘150%’(没有索引状况下) 效率比LIKE '%150'/LIKE '%150%'效率高很多

**Comment by zhonggy** [comment]
核心在于：索引的利用前提必须是有序的。
你可以类比查字典。

150这种前缀也是有顺序的，可以利用索引。
