### ISSUE TITLE
如何将不能公开的变量（如密钥）写进application.conf并访问？

### ISSUE THREAD

**Issue by UncleYangsir** [UncleYangsir/wuliuzha#9]
### 要将一些无法公开的内容写进application.conf并进行访问，其步骤应为以下几步：
**首先：**
```
Sms {
  accessKeyId="相对应的密钥Id"
  accessKeySecret="相对应的密码"
}
```
当然写入的语法要满足Play中application.conf使用的[HOCON](https://github.com/typesafehub/config/blob/master/HOCON.md)

**其次**
因为在Play2.4版本很多类都被启用，而最新的Play是推荐用依赖注入的方式访问，所以在相应的类中应该注入要访问application.conf的类play.api.Configuration configuration，如此就可以访问相应的变量；
```
static private String accessKeyId;
static private String accessKeySecret;
@Inject
public SmsDemo(play.api.Configuration configuration ) {
      this.accessKeyId = configuration.underlying().getString("SmsDemo.accessKeyId");
      this.accessKeySecret = configuration.underlying().getString("SmsDemo.accessKeySecret");
}
```
这样就可以获取写入application.conf的变量

**最后**
解决问题的思路：
目的：将需要隐藏的/不能公开的密钥或变量写入application.conf并在类中，并在相应的类中将application.conf内的相应写入值赋值给相应的变量；
所以需要解决的问题：

- 如何将相关变量写入application.conf中，并且需要注意什么？
[HOCON语法](https://github.com/typesafehub/config/blob/master/HOCON.md)
- playframework如何访问application.conf中的变量？
根据[访问Play!application.conf中的变量](https://gxnotes.com/article/39891.html)，在这里面找到了[play2.5迁移指南](https://www.playframework.com/documentation/2.6.x/Migration25#Deprecated-play.Play-and-play.api.Play-methods)并在其中获取了关键代码
```
class HomeController @Inject() (environment: play.api.Environment,
    configuration: play.api.Configuration)
  extends Controller {

  def index = Action {
    Ok(views.html.index("Your new application is ready."))
  }

  def config = Action {
    Ok(configuration.underlying.getString("some.config"))
  }

  def count = Action {
    val num = environment.resource("application.conf").toSeq.size
    Ok(num.toString)
  }
}
```
这是scala中的代码，因为java和scala中的代码相似，我就将其转换成了
```
import javax.inject.*;
....
static private String accessKeyId;
static private String accessKeySecret;
@Inject
public SmsDemo(play.api.Configuration configuration ) {
      this.accessKeyId = configuration.underlying().getString("SmsDemo.accessKeyId");
      this.accessKeySecret = configuration.underlying().getString("SmsDemo.accessKeySecret");
}
```
### 完成

**Comment by zhonggy** [comment]
不错！
